spring:
#  數據庫連接配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:5678/bookdb
    username: root
    password: h124507595
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置日期格式化
  jackson:
    date-format: yyyy-MM-dd
  # 設置MyBatis-plus全局配置
  web:
    resources:
      static-locations: classpath:/resources,classpath:/static,classpath:/public,file:C://bookimgs,file:C://HeaderImgs
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #     設置實體類對應的表格的統一前綴
      table-prefix: t_
      #     統一主鍵生成策略
      id-type: auto
server:
  port: 8090